
// on load
const DB_KEY = 'butterfly_wings';
const SETUP_KEY = "setup0"
const WING_LIST = [
    "Glymphatic clearance",
    "CRISPR origins",
    "Antikythera mechanism",
    "Cuttlefish camouflage",
    "Gesture origins",
    "Phage therapy",
    "Sensory substitution",
    "London smog",
    "Ion pumps",
    "Pareidolia faces",
    "Zombie fungi",
    "Voynich manuscript",
    "Placebo chemistry",
    "Bioluminescence evolution",
    "Tunguska mystery",
    "Vicarious learning",
    "Quantum entanglement",
    "lncRNA regulation",
    "Rosetta unlocking",
    "Avian magnetoreception",
    "Nocebo effects",
    "Mitochondrial Eve",
    "Spatial neglect",
    "Rogue waves",
    "Black Death",
    "Gut–brain axis",
    "Monty Hall",
    "Tardigrade cryptobiosis",
    "Forgery detection",
    "Eusociality dynamics",
    "Manhattan Project",
    "Hebbian learning",
    "Randomized trials",
    "Hydrothermal vents",
    "Sokal affair",
    "Cryptic choice",
    "Dreyfus affair",
    "Optogenetics control",
    "Uncanny valley",
    "Basal ganglia",
    "JFK conspiracies",
    "Paleoclimatology cores",
    "Transposable elements",
    "Tunnel safety",
    "Pareto distributions",
    "Endosymbiosis theory",
    "Memory reconsolidation",
    "Cichlid radiation",
    "Banned books",
    "Adult neurogenesis",
    "Caesar cipher",
    "Anthropogenic extinctions",
    "Mirror recognition",
    "Lindy effect",
    "Epigenetic inheritance",
    "10,000-year clock",
    "Hox genes",
    "Other-race effect",
    "Boltzmann brains",
    "Limits to Growth",
    "Glial functions",
    "Radium hazards",
    "Color constancy",
    "Suez Crisis",
    "Punctuated equilibrium",
    "Placebo analgesia",
    "Ant-fungus farming",
    "Bhopal disaster",
    "Mushroom toxins",
    "Human echolocation",
    "Movable type",
    "Flynn effect",
    "Nearly neutral",
    "Tang dynasty",
    "Trophic cascades",
    "Blind mole-rat",
    "1918 influenza",
    "FACS system",
    "REM consolidation",
    "Dark matter",
    "Linear A",
    "Cognitive offloading",
    "Corvid intelligence",
    "Roswell incident",
    "Polygenic scores",
    "Panama Papers",
    "Human connectome",
    "Oxygenation events",
    "Phantom limb",
    "Subduction zones",
    "Roanoke mystery",
    "Paleolithic art",
    "Müller-Lyer illusion",
    "Prion proteins",
    "Fermi paradox",
    "Cultural evolution",
    "Gullah culture",
    "Hypergraph nets",
    "Deepfake forensics",
    "Ozone recovery",
    "Altruistic punishment",
    "Heterochrony shifts",
    "Gulf Stream",
    "Affect heuristic",
    "Paleogenomics",
    "Zheng He",
    "Epigenetic editing",
    "Urban heat-islands",
    "Creole emergence",
    "Loss aversion",
    "Brown fat",
    "God helmet",
    "Taiping Rebellion",
    "Microplastics spread",
    "Birdsong syntax",
    "Chernobyl wildlife",
    "Prosopagnosia cases",
    "Codon redundancy",
    "Anoxic extinctions",
    "Conspiracy psychology",
    "Thylacine extinction",
    "Quantum tunneling",
    "Bronze Age metallurgy",
    "Cognitive load",
    "Little Ice Age",
    "Neurovascular coupling",
    "Phineas Gage",
    "Mendelian vs. polygenic",
    "Mongol trade",
    "Critical periods",
    "RNA editing",
    "Cambridge Analytica",
    "Cryptozoology culture",
    "Anthropocene markers",
    "Boids flocking",
    "Consciousness theories",
    "Cholera reforms",
    "Lateral gene transfer",
    "Opsin polymorphism",
    "Letters of marque",
    "Predictive coding",
    "Mitochondrial replacement",
    "High-frequency trading",
    "Affordances concept",
    "Tuned mass dampers",
    "Aging biology",
    "Zika neuropathology",
    "Pheromone control",
    "Index censorship",
    "Predictive policing",
    "Self-domestication",
    "Harlem Renaissance",
    "Chaos theory",
    "fNIRS mobility",
    "Roman hydraulics",
    "Antifragility idea",
    "Exoplanet diversity",
    "Embodied cognition",
    "Glacial rebound",
    "Synaptic pruning",
    "Petri invention",
    "Japonisme influence",
    "Ketamine therapy",
    "Tulip mania",
    "Non-Euclidean geometry",
    "Hajj networks",
    "Optical tweezers",
    "Creativity networks",
    "RNA virus evolution",
    "Spartacist uprising",
    "GWAS limits",
    "Invasive species",
    "Vaccine history",
    "Confirmation bias",
    "Circadian genes",
    "Acoustic ecology",
    "Triangulation mapping",
    "McGurk effect",
    "Symbolic emergence",
    "Computational creativity",
    "Black swans",
    "microRNA roles",
    "Quorum sensing",
    "Easter Island",
    "Microbiome cultures",
    "Sleep paralysis",
    "Network motifs",
    "Enigma codebreaking",
    "Boredom cognition",
    "Microbial dark-matter",
    "Moral luck",
    "East India Company",
    "Retinal therapies",
    "Migration flyways",
    "Gentrification dynamics",
    "Cancer microRNAs",
    "Mammoth genomes",
    "Classical debates",
    "Boredom networks",
    "Self-organized criticality",
    "Human challenge ethics",
    "Kleptoplasty slugs",
    "Silk Road",
    "Identity complexity",
    "Cahokia city",
    "Humor neuroscience",
    "Comet organics",
    "1973 Chile",
    "Immune profiling",
    "Cultural capital",
    "Paleomagnetic flips",
    "Microglial pruning",
    "Taphonomy processes",
    "Scarcity psychology",
    "Augmented reality",
    "Eukaryote origin",
    "Göbekli Tepe",
    "Socioemotional selectivity",
    "2004 tsunami",
    "Quantum error-correction",
    "Unihemispheric sleep",
    "Tacit knowledge",
    "Meta-analysis bias",
    "IQ controversies",
    "Frog chorusing",
    "Lysenkoism lessons",
    "Meningeal lymphatics",
    "Music & memory",
    "Indus script",
    "Metaphor cognition",
    "Black hole paradox",
    "Language attrition",
    "Adaptive optics",
    "Attachment neurochemistry",
    "Facial-recognition ethics",
    "Cambrian explosion",
    "Heat-shock proteins",
    "Attention economy",
    "Mummification chemistry",
    "Sham surgery",
    "Laughter contagion",
    "Neolithic farming",
    "Anthrax letters",
    "Stochastic resonance",
    "Unsung women",
    "Language revitalization",
    "Molecular chaperones",
    "Whale acoustics",
    "Bayeux Tapestry",
    "Permafrost thaw",
    "Joint attention",
    "Predictive genomics",
    "Evolutionary games",
    "Chronic pain circuits",
    "Frequency illusion",
    "Taphonomic bias",
    "SSRI neurogenesis_replaced",
    "Rare-earth geopolitics",
    "Slavery archaeology",
    "Learned helplessness",
    "Behavioral nudges",
    "Built-environment microbiome",
    "Multilingual cognition",
    "Crypto history",
    "Bat reservoirs",
    "Gem formation",
    "Synaptic homeostasis",
    "Press diffusion",
    "Geoengineering debates",
    "Venom evolution",
    "Dead Sea Scrolls",
    "Weak ties",
    "Deception detection",
    "Microbial fuel cells",
    "Slave life archaeology",
    "Stroke plasticity",
    "Vowel shifts",
    "Museum tissue DNA",
    "Error-correcting math",
    "Manson impact",
    "Hypnosis neuroscience",
    "Urban green space",
    "Superantigens",
    "Columbian Exchange",
    "Structural coloration",
    "Science demarcation",
    "Neurolaw issues",
    "Device infections",
    "Trans-Saharan trade",
    "Neuroeconomics valuation",
    "Industrial archaeology",
    "Copy number variants",
    "Fermentation science",
    "SOX factors",
    "Mass psychogenic illness",
    "Lunar programs",
    "Skin pigmentation",
    "Stochastic expression",
    "Wunderkammer history",
    "Rumor dynamics",
    "Isotope migration",
    "Social reward",
    "Imperial espionage",
    "Gut virome",
    "Percolation theory",
    "Shipwreck archaeology",
    "Earworms mechanism",
    "Tea & coffee",
    "Membrane fusion",
    "Ottoman millet",
    "Brain–computer interfaces",
    "African metallurgy",
    "Antibiotic epidemiology",
    "Moral cognition",
    "Exaptation examples",
    "Internet governance",
    "Cheetah biomechanics",
    "Pre-Columbian contacts",
    "Gut peptides",
    "Costly signaling",
    "Bomb-pulse isotopes",
    "Antibiotic arms-race",
    "Habeas corpus",
    "Microgravity physiology",
    "Flow states",
    "Social robots",
    "Keystone species",
    "Fake-news ecosystems",
    "Trepanation history",
    "Coral bleaching",
    "Gift economies",
    "Ancient roads",
    "Temporal representation",
    "Germline editing",
    "Whistleblowing dynamics",
    "SIR models",
    "Niche construction",
    "Map projections",
    "Addiction neurobiology",
    "Urban collapse",
    "Mycelial networks",
    "Fluvial engineering",
    "Heat-shock innovation",
    "Moral credentialing",
    "Dendrochronology dating",
    "Music origins",
    "Dendritic computing",
    "Epidemic stigma",
    "Trade winds",
    "Attention interplay",
    "Denisovan DNA",
    "AI alignment",
    "Phosphorus cycle",
    "HPA programming",
    "Fermentation spread",
    "Polynesian voyaging",
    "Moral panics",
    "Signal optimization",
    "Scientific frauds",
    "Citizen science",
    "Cultural lag",
    "Universal sleep",
    "Ocean acidification",
    "Automation impacts",
    "Bit rot",
    "Celebrity doubles",
    "NASA whistleblowers",
    "HAARP storms",
    "Chemtrail programs",
    "Titanic insurance claim",
    "Suppressed cure labs",
    "CERN portals myth",
    "Phantom islands",
    "Ancient astronaut claims",
    "Denver Airport murals",
    "Deep-state networks",
    "Pharma price-fixing",
    "Bilderberg influence",
    "MK-Ultra aftermath",
    "Tesla suppression",
    "Vatican hidden files",
    "Secret global ledger",
    "Hollywood predictive scripts",
    "Royal cloning rumor",
    "Underground elite cities",
    "Time-travel experiments",
    "Climate data fixes",
    "Crop-circle hoaxes",
    "Synthetic food coverup",
    "Earthquake weaponization",
    "Artificial moon theory",
    "Giant skeletons coverup",
    "Alien hybrid program",
    "Secret space fleets",
    "Erased towns mystery",
    "Nuclear coverups",
    "Presidential doubles",
    "Cult infiltration politics",
    "Monarch programming claims",
    "Antarctic mining secrecy",
    "Global vote rigging",
    "Shadow corporate rule",
    "Thought-language programs",
    "Art coordinate codes",
    "Hidden library caches",
    "Olympic bribery rings",
    "Microchip rumor history",
    "Satellite swap hoax",
    "Deepfake governance",
    "Elite railroad networks",
    "Prison islands secret",
    "Longevity island labs",
    "Mind-control patents",
    "Gene-patent secrecy",
    "Cloned soldier units",
    "Alien visitation treaties",
    "Private moon colonies",
    "Star-chart art codes",
    "Market manipulation rings",
    "Offshore private islands",
    "Alternative seed vaults",
    "Social-media psyops",
    "Mass-surveillance rituals",
    "Faux protests operations",
    "Currency microtext codes",
    "Royal bloodline fraud",
    "Capital tunnel maps",
    "Meteor impact coverups",
    "Monument vault conspiracies",
    "Archaeological hoaxes",
    "Ghost cities for wealthy",
    "Manufactured pandemic theory",
    "Organ-trafficking networks",
    "Elite gene-editing labs",
    "Asteroid-mining deals",
    "Psychic-program experiments",
    "Emoji hidden language",
    "Corporate weather patents",
    "Secret submarine bases",
    "Underground elite hospitals",
    "Memory-farming studios",
    "Astronaut biosphere fakery",
    "Coded folk-songs",
    "Shapeshifting rumor sites",
    "Court ruling erasures",
    "Underground seed vaults",
    "Black-budget resorts",
    "Psychotropic water plots",
    "Private wildlife collections",
    "Desert machine myths",
    "Mountain vault complexes",
    "Sleeper-artist programs",
    "Private orbital habitats",
    "Bioweapon origin coverups",
    "DNA watermark claims",
    "Royal vault caches",
    "Covert cloning farms",
    "Thought-reading patents",
    "Tourist dig falsifications",
    "Exile island systems",
    "Pandemic-simulation leaks",
    "Elite off-grid towns",
    "Subsea rail rumors",
    "Backdoor voting systems",
    "Shadow currency backers",
]
let db = JSON.parse(localStorage.getItem(DB_KEY) || '{}');

function saveDb(db) {
    localStorage.setItem(DB_KEY, JSON.stringify(db));
}

function initialze() {
    if (!getValue(SETUP_KEY)) {
        localStorage.removeItem(DB_KEY);
        db = JSON.parse(localStorage.getItem(DB_KEY) || '{}');
        console.log('setting up db', db);
        WING_LIST.forEach(wing => {
            setValue(wing, false);
        });
        console.log('current db', db);
        setValue(SETUP_KEY, true);
        saveDb(db);
    }
}

// read
function getValue(key) {
    return !!db[key];
}

// write
function setValue(key, boolVal) {
    db[key] = !!boolVal;
}

// delete
function deleteValue(key) {
    delete db[key];
}


function getRandomFalseKey() {
    const falseKeys = Object.keys(db).filter(k => !!db[k] === false);
    if (falseKeys.length === 0) return null; // no false items
    const randomIndex = Math.floor(Math.random() * falseKeys.length);
    return falseKeys[randomIndex];
}

// example usage
document.addEventListener("DOMContentLoaded", () => {
    const randomKey = getRandomFalseKey();
    if (randomKey) {
        setValue(randomKey, true);
        document.getElementById("prompt-text").textContent = randomKey;
        saveDb(db);
    } else {
        document.getElementById("prompt-text").textContent = "You've researched everything tinki :))))";
    }
    console.log("db now", db)
});

initialze();
